### ISSUE TITLE
Crash at cue point type conversion

### ISSUE THREAD

**Issue by negimeister** [kimtore/rex#3]
Hi, thanks for this awesome project.
I tried exporting my (potentially janky) Mixxx library, but it crashes with this error:

`fatal error: sql: Scan error on column index 13, name "cuepoint": converting driver.Value type float64 ("1.6380503069767442e+07") to a int64: invalid syntax`

I'll try looking into it more deeply in a few days to figure out which track is causing this.

**Comment by kimtore** [comment]
Hi @negimeister, thanks for the bug report.
I've pushed a commit I believe will fix this issue.

**Comment by negimeister** [comment]
That was quick!
Not sure if I'm looking in the right place, but I can only see the `github` branch that doesn't have any recent commits.

**Comment by kimtore** [comment]
Sorry, my bad, pushed to a different repo. Try now :)

**Comment by negimeister** [comment]
Thanks, it's exporting now! I might be able to test it on a CDJ-3000 next week. I'll report back if I do
